
package br.com.caelum.estoque.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://caelum.com.br/estoquews/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addItemEstoque", targetNamespace = "http://caelum.com.br/estoquews/v1", className = "br.com.caelum.estoque.soap.AddItemEstoque")
    @ResponseWrapper(localName = "addItemEstoqueResponse", targetNamespace = "http://caelum.com.br/estoquews/v1", className = "br.com.caelum.estoque.soap.AddItemEstoqueResponse")
    public String addItemEstoque(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param tokenUsuario
     * @param parameters
     * @return
     *     returns br.com.caelum.estoque.soap.ItensPeloCodigoResponse
     * @throws AutorizacaoException
     */
    @WebMethod(operationName = "ItensPeloCodigo")
    @WebResult(name = "ItensPeloCodigoResponse", targetNamespace = "http://caelum.com.br/estoquews/v1", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ItensPeloCodigoResponse itensPeloCodigo(
        @WebParam(name = "ItensPeloCodigo", targetNamespace = "http://caelum.com.br/estoquews/v1", partName = "parameters")
        ItensPeloCodigo parameters,
        @WebParam(name = "tokenUsuario", targetNamespace = "http://caelum.com.br/estoquews/v1", header = true, partName = "tokenUsuario")
        String tokenUsuario)
        throws AutorizacaoException
    ;

}
